import type { NextPage } from 'next';
import type { User } from '../types';
import Head from 'next/head';
import useSWR from 'swr';
import axios from 'axios';
import Link from 'next/link';

const Home: NextPage = () => {
  const fetcher = (url: string) => axios.get(url).then((res) => res.data);

  const { data, error } = useSWR<User[]>('/api/users', fetcher);

  if (!data && !error) return <div>Loading ...</div>;

  return (
    <div>
      <Head>
        <title>WebAuthn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Link href="register">Sign up</Link>
        <Link href="login">Sign in</Link>
      </header>

      <main>
        <h1 className="text-3xl font-bold underline">Web Authentication API</h1>
        <ul>
          {data ? (
            data.map((user) => (
              <li key={user.id}>
                <p>{user.username}</p>
                <p>{user.email}</p>
              </li>
            ))
          ) : (
            <p>No users</p>
          )}
        </ul>
      </main>
    </div>
  );
};

export default Home;
